name: ci

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish
      run: |
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/.npmrc
        npm publish --access public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
