name: ci

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+(\.[0-9]+)*/

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    if: |
      contains('refs/heads/master', github.ref)
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish
      run: |
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/.npmrc
        npm publish --access public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
